gfx/env/csgo_dustbk.tga
gfx/env/csgo_dustdn.tga
gfx/env/csgo_dustft.tga
gfx/env/csgo_dustlf.tga
gfx/env/csgo_dustrt.tga
gfx/env/csgo_dustup.tga
models/de_mirage_cs2/apc_gray.mdl
models/de_mirage_cs2/bg_sopa01.mdl
models/de_mirage_cs2/branches03.mdl
models/de_mirage_cs2/cart01_small.mdl
models/de_mirage_cs2/ClayPot02.mdl
models/de_mirage_cs2/datepalm.mdl
models/de_mirage_cs2/divan1.mdl
models/de_mirage_cs2/green_tarp.mdl
models/de_mirage_cs2/maniak_skomeyka01.mdl
models/de_mirage_cs2/pi_fern.mdl
models/de_mirage_cs2/prop_rimpalm1b.mdl
models/de_mirage_cs2/red_tarp2.mdl
models/de_mirage_cs2/red_tarp3.mdl
models/de_mirage_cs2/red_tarp4.mdl
models/de_mirage_cs2/van.mdl
sound/de_mirage_cs2/bg_mirage_01.wav
